cloudfoundry/multiapps

- .travis.yml
- com.sap.activiti.common/pom.xml
- com.sap.lmsl.slp.java/pom.xml
- pom.xml
Change-Id: I13617533cb1efd83ba86425e93dfe992939b2f5d
> Add .travis.yml

- .travis.settings.xml
- .travis.yml
Change-Id: Ie3d895ba7a954ebaee9b4aabea9bd2747f29640c
> Add support for publishing SNAPSHOT

- pom.xml
Change-Id: I42dc5e2cf8e4b13db2f8cfa000e40015df43f70f
> Refer to non-SNAPSHOT versions

- com.sap.activiti.common/pom.xml
- com.sap.lmsl.slp.java/pom.xml
- pom.xml
Change-Id: I611b0f43a3fa7e756f200bb08c4ac75f6a6d7f43
> Add nexus release plugin

- com.sap.cloud.lm.sl.common/src/main/java/com/sap/cloud/lm/sl/common/util/JsonUtil.java
Change-Id: If93c8d6495bdead9103783901153537a57506c96
> Add methods from GsonHelper due to removal of activiti.common

- com.sap.cloud.lm.sl.persistence/src/main/java/com/sap/cloud/lm/sl/persistence/message/Messages.java
- com.sap.cloud.lm.sl.persistence/src/main/java/com/sap/cloud/lm/sl/persistence/services/AbstractFileService.java
- com.sap.cloud.lm.sl.persistence/src/main/java/com/sap/cloud/lm/sl/persistence/services/DatabaseFileService.java
- com.sap.cloud.lm.sl.persistence/src/main/java/com/sap/cloud/lm/sl/persistence/services/FileSystemFileService.java
- com.sap.cloud.lm.sl.persistence/src/main/java/com/sap/cloud/lm/sl/persistence/services/ProcessLogsService.java
- com.sap.cloud.lm.sl.persistence/src/main/java/com/sap/cloud/lm/sl/persistence/services/ProgressMessageService.java
- com.sap.cloud.lm.sl.persistence/src/test/java/com/sap/cloud/lm/sl/persistence/services/DatabaseFileServiceTest.java
- com.sap.cloud.lm.sl.persistence/src/test/java/com/sap/cloud/lm/sl/persistence/services/FileSystemFileServiceTest.java
- com.sap.cloud.lm.sl.persistence/src/test/java/com/sap/cloud/lm/sl/persistence/services/ProgressMessageServiceTest.java
> Clean up old entries from DB and FS

- .travis.yml
- com.sap.cloud.lm.sl.common/src/main/java/com/sap/cloud/lm/sl/common/util/CommonUtil.java
- com.sap.cloud.lm.sl.persistence/src/main/java/com/sap/cloud/lm/sl/persistence/services/DatabaseFileService.java
- com.sap.cloud.lm.sl.persistence/src/main/java/com/sap/cloud/lm/sl/persistence/services/ProcessLogsService.java
- com.sap.cloud.lm.sl.persistence/src/main/java/com/sap/cloud/lm/sl/persistence/services/ProgressMessageService.java
> Clean Up Job: Fix compilation error

- com.sap.cloud.lm.sl.mta/src/main/java/com/sap/cloud/lm/sl/mta/handlers/HandlerFactory.java
> Change constant to be final

- com.sap.cloud.lm.sl.common/src/main/java/com/sap/cloud/lm/sl/common/model/xml/MapWrapper.java
- com.sap.cloud.lm.sl.common/src/main/java/com/sap/cloud/lm/sl/common/util/XmlUtil.java
Change-Id: Ib891aa20e0b82ae49f3533eb4978344ef4b8cab5
> Fix minor issues in XmlUtil

- com.sap.cloud.lm.sl.persistence/src/main/java/com/sap/cloud/lm/sl/persistence/services/AbstractFileService.java
Fortify finding, where multiple calls to getInputStream over the same file resource will return different input streams.
> Return the same InputStream on subsequent calls

- com.sap.cloud.lm.sl.common/src/main/java/com/sap/cloud/lm/sl/common/model/json/PropertiesAdapterFactory.java
- com.sap.cloud.lm.sl.common/src/main/java/com/sap/cloud/lm/sl/common/util/JsonUtil.java
- com.sap.cloud.lm.sl.common/src/test/java/com/sap/cloud/lm/sl/common/model/json/PropertiesAdapterFactoryTest.java
> Support integer values for service creation params

- com.sap.cloud.lm.sl.persistence/src/main/java/com/sap/cloud/lm/sl/persistence/message/Messages.java
- com.sap.cloud.lm.sl.persistence/src/main/java/com/sap/cloud/lm/sl/persistence/services/AbstractFileService.java
- com.sap.cloud.lm.sl.persistence/src/main/java/com/sap/cloud/lm/sl/persistence/services/FileSystemFileService.java
- com.sap.cloud.lm.sl.persistence/src/test/java/com/sap/cloud/lm/sl/persistence/services/DatabaseFileServiceTest.java
- com.sap.cloud.lm.sl.persistence/src/test/java/com/sap/cloud/lm/sl/persistence/services/FileSystemFileServiceTest.java
> Cleanup job: Remove orhpaned files in file system

- com.sap.cloud.lm.sl.persistence/src/main/java/com/sap/cloud/lm/sl/persistence/changes/AsyncChange.java
- com.sap.cloud.lm.sl.persistence/src/main/java/com/sap/cloud/lm/sl/persistence/changes/liquibase/AbstractChange.java
- com.sap.cloud.lm.sl.persistence/src/main/java/com/sap/cloud/lm/sl/persistence/changes/liquibase/AbstractDataTransformationChange.java
- com.sap.cloud.lm.sl.persistence/src/main/java/com/sap/cloud/lm/sl/persistence/services/SqlExecutor.java
Requires PostgreSQL 9.5 in order to work!
> Index process IDs of progress messages (Part 1)

- .travis.yml
Change-Id: Ibc212f03b290a1434285dfb8925117d2ed336f87
> Dedicated sonar dashboards for PR

- com.sap.cloud.lm.sl.mta/src/main/java/com/sap/cloud/lm/sl/mta/handlers/v3_1/HandlerConstructor.java
- com.sap.cloud.lm.sl.mta/src/main/java/com/sap/cloud/lm/sl/mta/resolvers/v2_0/DescriptorPlaceholderResolver.java
- com.sap.cloud.lm.sl.mta/src/main/java/com/sap/cloud/lm/sl/mta/resolvers/v2_0/ModulePlaceholderResolver.java
- com.sap.cloud.lm.sl.mta/src/main/java/com/sap/cloud/lm/sl/mta/resolvers/v2_0/ProvidedDependencyPlaceholderResolver.java
- com.sap.cloud.lm.sl.mta/src/main/java/com/sap/cloud/lm/sl/mta/resolvers/v3_1/DescriptorPlaceholderResolver.java
- com.sap.cloud.lm.sl.mta/src/main/java/com/sap/cloud/lm/sl/mta/resolvers/v3_1/ModulePlaceholderResolver.java
- com.sap.cloud.lm.sl.mta/src/main/java/com/sap/cloud/lm/sl/mta/resolvers/v3_1/ProvidedDependencyPlaceholderResolver.java
- com.sap.cloud.lm.sl.mta/src/test/java/com/sap/cloud/lm/sl/mta/resolvers/v2_0/DescriptorPlaceholderResolverTest.java
- com.sap.cloud.lm.sl.mta/src/test/java/com/sap/cloud/lm/sl/mta/resolvers/v3_1/DescriptorPlaceholderResolverTest.java
- com.sap.cloud.lm.sl.mta/src/test/resources/com/sap/cloud/lm/sl/mta/resolvers/v3_1/mtad-01.yaml
- com.sap.cloud.lm.sl.mta/src/test/resources/com/sap/cloud/lm/sl/mta/resolvers/v3_1/platform-1.json
- com.sap.cloud.lm.sl.mta/src/test/resources/com/sap/cloud/lm/sl/mta/resolvers/v3_1/result-01.json
- com.sap.cloud.lm.sl.mta/src/test/resources/com/sap/cloud/lm/sl/mta/resolvers/v3_1/system-parameters.json
- com.sap.cloud.lm.sl.mta/src/test/resources/com/sap/cloud/lm/sl/mta/resolvers/v3_1/target.json
> Add Placeholder resolver for parameters in provided dependencies

- com.sap.cloud.lm.sl.persistence/src/test/java/com/sap/cloud/lm/sl/persistence/services/ProgressMessageServiceTest.java
> Add unit test for ProgressMessageService.update()

- com.sap.cloud.lm.sl.persistence/src/main/java/com/sap/cloud/lm/sl/persistence/model/FileEntry.java
- com.sap.cloud.lm.sl.persistence/src/main/java/com/sap/cloud/lm/sl/persistence/services/AbstractFileService.java
- com.sap.cloud.lm.sl.persistence/src/main/java/com/sap/cloud/lm/sl/persistence/services/FileSystemFileService.java
- com.sap.cloud.lm.sl.persistence/src/test/java/com/sap/cloud/lm/sl/persistence/services/FileSystemFileServiceTest.java
The reason for this logging is for further analysis of NPE
NGPBUG-54679
> Add logging of created and founded file entries

- com.sap.cloud.lm.sl.persistence/src/main/java/com/sap/cloud/lm/sl/persistence/services/FileSystemFileService.java
- com.sap.cloud.lm.sl.persistence/src/test/java/com/sap/cloud/lm/sl/persistence/services/FileSystemFileServiceTest.java
JIRA: LMCROSSITXSADEPLOY-984
JIRA: LMCROSSITXSADEPLOY-1110
> Skip calling deleteOrphanedAttributes method if FileEntry is null

- com.sap.cloud.lm.sl.persistence/src/main/java/com/sap/cloud/lm/sl/persistence/message/Messages.java
- com.sap.cloud.lm.sl.persistence/src/main/java/com/sap/cloud/lm/sl/persistence/services/AbstractFileService.java
- com.sap.cloud.lm.sl.persistence/src/main/java/com/sap/cloud/lm/sl/persistence/services/FileSystemFileService.java
- com.sap.cloud.lm.sl.persistence/src/test/java/com/sap/cloud/lm/sl/persistence/services/DatabaseFileServiceTest.java
- com.sap.cloud.lm.sl.persistence/src/test/java/com/sap/cloud/lm/sl/persistence/services/FileSystemFileServiceTest.java
> Cleanup job to delete all old files

- com.sap.cloud.lm.sl.common/src/main/java/com/sap/cloud/lm/sl/common/model/json/MapWithNumbersAdapterFactory.java
- com.sap.cloud.lm.sl.common/src/main/java/com/sap/cloud/lm/sl/common/util/JsonUtil.java
- com.sap.cloud.lm.sl.common/src/test/java/com/sap/cloud/lm/sl/common/model/json/MapWithNumbersAdapterFactoryTest.java
- com.sap.cloud.lm.sl.mta/src/main/java/com/sap/cloud/lm/sl/mta/model/SystemParameters.java
> Parse JSONs properly

- com.sap.cloud.lm.sl.common/pom.xml
- com.sap.cloud.lm.sl.mta/pom.xml
- pom.xml
Change-Id: Ib45904776e7cc476b42ac2fef62f121534e888c7
> Set version to 1.64.0

- com.sap.cloud.lm.sl.common/pom.xml
- com.sap.cloud.lm.sl.mta/pom.xml
- pom.xml
Change-Id: I270d2fe47bf2ded7b4815e223d5c6c0800f60502
> Set version to 1.65.0-SNAPSHOT

- spec/schemas/v3/v3.2/exttest.yaml
- spec/schemas/v3/v3.2/mta-schema.yaml
- spec/schemas/v3/v3.2/mtaext-schema.yaml
- spec/schemas/v3/v3.2/test.yaml
> Specification 3.2

- com.sap.cloud.lm.sl.common/src/test/java/com/sap/cloud/lm/sl/common/util/TestUtil.java
- com.sap.cloud.lm.sl.mta/src/main/java/com/sap/cloud/lm/sl/mta/handlers/v2/Schemas.java
- com.sap.cloud.lm.sl.mta/src/main/java/com/sap/cloud/lm/sl/mta/handlers/v3/Schemas.java
- com.sap.cloud.lm.sl.mta/src/main/java/com/sap/cloud/lm/sl/mta/model/v1/ExtensionDescriptor.java
- com.sap.cloud.lm.sl.mta/src/main/java/com/sap/cloud/lm/sl/mta/model/v2/ExtensionDescriptor.java
- com.sap.cloud.lm.sl.mta/src/main/java/com/sap/cloud/lm/sl/mta/model/v3/ExtensionDescriptor.java
- com.sap.cloud.lm.sl.mta/src/main/java/com/sap/cloud/lm/sl/mta/parsers/v1/ExtensionDescriptorParser.java
- com.sap.cloud.lm.sl.mta/src/main/java/com/sap/cloud/lm/sl/mta/parsers/v2/ExtensionDescriptorParser.java
- com.sap.cloud.lm.sl.mta/src/main/java/com/sap/cloud/lm/sl/mta/parsers/v3/ExtensionDescriptorParser.java
- com.sap.cloud.lm.sl.mta/src/test/resources/com/sap/cloud/lm/sl/mta/handlers/v3/config-00.mtaext
- com.sap.cloud.lm.sl.mta/src/test/resources/com/sap/cloud/lm/sl/mta/handlers/v3/config-01.mtaext
- com.sap.cloud.lm.sl.mta/src/test/resources/com/sap/cloud/lm/sl/mta/handlers/v3/parsed-config-00.mtaext
- com.sap.cloud.lm.sl.mta/src/test/resources/com/sap/cloud/lm/sl/mta/handlers/v3/parsed-config-01.mtaext
- com.sap.cloud.lm.sl.mta/src/test/resources/com/sap/cloud/lm/sl/mta/serialization/v1/serialized-extension-00.json
- com.sap.cloud.lm.sl.mta/src/test/resources/com/sap/cloud/lm/sl/mta/serialization/v2/extension-descriptor-00.mtaext
- com.sap.cloud.lm.sl.mta/src/test/resources/com/sap/cloud/lm/sl/mta/serialization/v2/serialized-extension-00.json
- com.sap.cloud.lm.sl.mta/src/test/resources/com/sap/cloud/lm/sl/mta/serialization/v3/extension-descriptor-00.mtaext
- com.sap.cloud.lm.sl.mta/src/test/resources/com/sap/cloud/lm/sl/mta/serialization/v3/extension-descriptor-01.mtaext
- com.sap.cloud.lm.sl.mta/src/test/resources/com/sap/cloud/lm/sl/mta/serialization/v3/serialized-extension-00.json
- com.sap.cloud.lm.sl.mta/src/test/resources/com/sap/cloud/lm/sl/mta/serialization/v3/serialized-extension-01.json
> Fix handling of descriptions and providers

- com.sap.cloud.lm.sl.mta/src/main/java/com/sap/cloud/lm/sl/mta/model/SupportedVersions.java
> Add 3.2 spec to the supported versions

- com.sap.cloud.lm.sl.mta/src/main/java/com/sap/cloud/lm/sl/mta/model/SupportedVersions.java
- com.sap.cloud.lm.sl.mta/src/main/java/com/sap/cloud/lm/sl/mta/schema/SchemaValidator.java
- com.sap.cloud.lm.sl.mta/src/test/java/com/sap/cloud/lm/sl/mta/handlers/v2/ConfigurationParserTest.java
- com.sap.cloud.lm.sl.mta/src/test/java/com/sap/cloud/lm/sl/mta/schema/SchemaValidatorTest.java
- com.sap.cloud.lm.sl.mta/src/test/resources/com/sap/cloud/lm/sl/mta/handlers/v2/platform-02.json.json
- com.sap.cloud.lm.sl.mta/src/test/resources/com/sap/cloud/lm/sl/mta/schema/mtad-01.yaml
- com.sap.cloud.lm.sl.mta/src/test/resources/com/sap/cloud/lm/sl/mta/schema/mtad-02.yaml
Issue: LMCROSSITXSADEPLOY-1367
> Remove strict MTA schema validation

- com.sap.cloud.lm.sl.mta/src/main/java/com/sap/cloud/lm/sl/mta/message/Messages.java
> Error retrieving extension descriptor

- spec/schemas/v3/v3.1/mta-schema.yaml
- spec/schemas/v3/v3.1/mtaext-schema.yaml
- spec/schemas/v3/v3.1/test.yaml
- spec/schemas/v3/v3.2/mta-schema.yaml
- spec/schemas/v3/v3.2/mtaext-schema.yaml
> Document support for parameters in provided dependencies

- com.sap.cloud.lm.sl.common/src/test/java/com/sap/cloud/lm/sl/common/util/GenericArgumentMatcher.java
- com.sap.cloud.lm.sl.common/src/test/java/com/sap/cloud/lm/sl/common/util/TestCase.java
- com.sap.cloud.lm.sl.common/src/test/java/com/sap/cloud/lm/sl/common/util/TestUtil.java
- com.sap.cloud.lm.sl.common/src/test/java/com/sap/cloud/lm/sl/common/util/Tester.java
- com.sap.cloud.lm.sl.mta/src/test/java/com/sap/cloud/lm/sl/mta/builders/v2/ParametersChainBuilderTest.java
- com.sap.cloud.lm.sl.mta/src/test/java/com/sap/cloud/lm/sl/mta/builders/v2/PropertiesChainBuilderTest.java
- com.sap.cloud.lm.sl.mta/src/test/java/com/sap/cloud/lm/sl/mta/handlers/ConfigurationParserTest.java
- com.sap.cloud.lm.sl.mta/src/test/java/com/sap/cloud/lm/sl/mta/handlers/v2/DescriptorHandlerTest.java
- com.sap.cloud.lm.sl.mta/src/test/java/com/sap/cloud/lm/sl/mta/handlers/v2/DescriptorMergerTest.java
- com.sap.cloud.lm.sl.mta/src/test/java/com/sap/cloud/lm/sl/mta/handlers/v2/DescriptorParserTest.java
- com.sap.cloud.lm.sl.mta/src/test/java/com/sap/cloud/lm/sl/mta/handlers/v2/DescriptorValidatorTest.java
- com.sap.cloud.lm.sl.mta/src/test/java/com/sap/cloud/lm/sl/mta/handlers/v3/DescriptorHandlerTest.java
- com.sap.cloud.lm.sl.mta/src/test/java/com/sap/cloud/lm/sl/mta/handlers/v3/DescriptorMergerTest.java
- com.sap.cloud.lm.sl.mta/src/test/java/com/sap/cloud/lm/sl/mta/handlers/v3/DescriptorParserTest.java
- com.sap.cloud.lm.sl.mta/src/test/java/com/sap/cloud/lm/sl/mta/handlers/v3/DescriptorValidatorTest.java
- com.sap.cloud.lm.sl.mta/src/test/java/com/sap/cloud/lm/sl/mta/mergers/PlatformMergerTest.java
- com.sap.cloud.lm.sl.mta/src/test/java/com/sap/cloud/lm/sl/mta/resolvers/PropertiesResolverTest.java
- com.sap.cloud.lm.sl.mta/src/test/java/com/sap/cloud/lm/sl/mta/resolvers/v2/DescriptorPlaceholderResolverTest.java
- com.sap.cloud.lm.sl.mta/src/test/java/com/sap/cloud/lm/sl/mta/resolvers/v2/DescriptorReferenceResolverTest.java
- com.sap.cloud.lm.sl.mta/src/test/java/com/sap/cloud/lm/sl/mta/resolvers/v3/DescriptorReferenceResolverTest.java
- com.sap.cloud.lm.sl.mta/src/test/java/com/sap/cloud/lm/sl/mta/schema/SchemaValidatorTest.java
- com.sap.cloud.lm.sl.mta/src/test/java/com/sap/cloud/lm/sl/mta/serialization/v2/DescriptorSerializationTest.java
- com.sap.cloud.lm.sl.mta/src/test/java/com/sap/cloud/lm/sl/mta/serialization/v3/DescriptorSerializationTest.java
- com.sap.cloud.lm.sl.mta/src/test/java/com/sap/cloud/lm/sl/mta/util/PropertiesUtilTest.java
> Extract test() methods from TestUtil

- spec/schemas/v3/v3.3/exttest.yaml
- spec/schemas/v3/v3.3/mta-schema.yaml
- spec/schemas/v3/v3.3/mtaext-schema.yaml
- spec/schemas/v3/v3.3/test.yaml
> Add schema files for MTA spec 3.3

- pom.xml
Whitesource maven plugin help to identify which are the
direct FOSS components
> Add whitesource integration

- .travis.yml
> Fix travis to use java 8

- com.sap.cloud.lm.sl.mta/src/test/java/com/sap/cloud/lm/sl/mta/util/PropertiesUtilTest.java
Unit tests for the GetPluralOrSingular method of PropertiesUtil
Related to: LMCROSSITXSADEPLOY-1558
> Add more unit tests for PropertiesUtil

- com.sap.cloud.lm.sl.common/src/main/java/com/sap/cloud/lm/sl/common/util/JsonUtil.java
> Avoid expensive creation of Jackson object mappers

- com.sap.cloud.lm.sl.mta/src/main/java/com/sap/cloud/lm/sl/mta/model/Hook.java
- com.sap.cloud.lm.sl.mta/src/main/java/com/sap/cloud/lm/sl/mta/model/Visitor.java
- com.sap.cloud.lm.sl.mta/src/main/java/com/sap/cloud/lm/sl/mta/resolvers/ReferencePattern.java
- com.sap.cloud.lm.sl.mta/src/main/java/com/sap/cloud/lm/sl/mta/resolvers/ReferencesUnescaper.java
- com.sap.cloud.lm.sl.mta/src/test/java/com/sap/cloud/lm/sl/mta/resolvers/v2/DescriptorPlaceholderResolverTest.java
- com.sap.cloud.lm.sl.mta/src/test/java/com/sap/cloud/lm/sl/mta/resolvers/v2/DescriptorReferenceResolverTest.java
- com.sap.cloud.lm.sl.mta/src/test/java/com/sap/cloud/lm/sl/mta/resolvers/v2/ReferencesUnescaperTest.java
- com.sap.cloud.lm.sl.mta/src/test/java/com/sap/cloud/lm/sl/mta/resolvers/v3/DescriptorPlaceholderResolverTest.java
- com.sap.cloud.lm.sl.mta/src/test/java/com/sap/cloud/lm/sl/mta/resolvers/v3/DescriptorReferenceResolverTest.java
- com.sap.cloud.lm.sl.mta/src/test/java/com/sap/cloud/lm/sl/mta/resolvers/v3/ReferencesUnescaperTest.java
- com.sap.cloud.lm.sl.mta/src/test/resources/com/sap/cloud/lm/sl/mta/resolvers/v2/mtad-with-escaped-placeholders.yaml
- com.sap.cloud.lm.sl.mta/src/test/resources/com/sap/cloud/lm/sl/mta/resolvers/v2/mtad-with-escaped-references.yaml
- com.sap.cloud.lm.sl.mta/src/test/resources/com/sap/cloud/lm/sl/mta/resolvers/v2/result-from-escaped-placeholders.json
- com.sap.cloud.lm.sl.mta/src/test/resources/com/sap/cloud/lm/sl/mta/resolvers/v2/result-from-escaped-references.json
- com.sap.cloud.lm.sl.mta/src/test/resources/com/sap/cloud/lm/sl/mta/resolvers/v2/result-from-unescaping-placeholders.json
- com.sap.cloud.lm.sl.mta/src/test/resources/com/sap/cloud/lm/sl/mta/resolvers/v2/result-from-unescaping-references.json
- com.sap.cloud.lm.sl.mta/src/test/resources/com/sap/cloud/lm/sl/mta/resolvers/v3/mtad-with-escaped-placeholders.yaml
- com.sap.cloud.lm.sl.mta/src/test/resources/com/sap/cloud/lm/sl/mta/resolvers/v3/mtad-with-escaped-references.yaml
- com.sap.cloud.lm.sl.mta/src/test/resources/com/sap/cloud/lm/sl/mta/resolvers/v3/result-from-escaped-placeholders.json
- com.sap.cloud.lm.sl.mta/src/test/resources/com/sap/cloud/lm/sl/mta/resolvers/v3/result-from-escaped-references.json
- com.sap.cloud.lm.sl.mta/src/test/resources/com/sap/cloud/lm/sl/mta/resolvers/v3/result-from-unescaping-placeholders.json
- com.sap.cloud.lm.sl.mta/src/test/resources/com/sap/cloud/lm/sl/mta/resolvers/v3/result-from-unescaping-references.json
> Allow escaping of references and placeholders

- pom.xml
Use fixed version for whitesource project
Otherwise for each new release, there will be more and more whitesource projects which will be hard for support.
> Use fixed version for whitesource scan

- .gitignore
- com.sap.cloud.lm.sl.mta/src/main/java/com/sap/cloud/lm/sl/mta/builders/v2/ParametersChainBuilder.java
- com.sap.cloud.lm.sl.mta/src/main/java/com/sap/cloud/lm/sl/mta/builders/v2/PropertiesChainBuilder.java
- com.sap.cloud.lm.sl.mta/src/main/java/com/sap/cloud/lm/sl/mta/builders/v3/ModuleDependenciesCollector.java
- com.sap.cloud.lm.sl.mta/src/main/java/com/sap/cloud/lm/sl/mta/handlers/v2/ModulesSorter.java
- com.sap.cloud.lm.sl.mta/src/main/java/com/sap/cloud/lm/sl/mta/handlers/v3/DescriptorValidator.java
- com.sap.cloud.lm.sl.mta/src/main/java/com/sap/cloud/lm/sl/mta/handlers/v3/ModulesSorter.java
- com.sap.cloud.lm.sl.mta/src/main/java/com/sap/cloud/lm/sl/mta/model/VersionRule.java
- com.sap.cloud.lm.sl.mta/src/main/java/com/sap/cloud/lm/sl/mta/resolvers/PatternResolver.java
- com.sap.cloud.lm.sl.mta/src/main/java/com/sap/cloud/lm/sl/mta/resolvers/PropertiesPlaceholderResolver.java
- com.sap.cloud.lm.sl.mta/src/main/java/com/sap/cloud/lm/sl/mta/resolvers/PropertiesResolver.java
- com.sap.cloud.lm.sl.mta/src/main/java/com/sap/cloud/lm/sl/mta/resolvers/ReferencePattern.java
- com.sap.cloud.lm.sl.mta/src/main/java/com/sap/cloud/lm/sl/mta/resolvers/ReferenceResolver.java
- com.sap.cloud.lm.sl.mta/src/main/java/com/sap/cloud/lm/sl/mta/resolvers/v2/DescriptorPlaceholderResolver.java
- com.sap.cloud.lm.sl.mta/src/main/java/com/sap/cloud/lm/sl/mta/resolvers/v2/DescriptorReferenceResolver.java
- com.sap.cloud.lm.sl.mta/src/main/java/com/sap/cloud/lm/sl/mta/resolvers/v2/ModulePlaceholderResolver.java
- com.sap.cloud.lm.sl.mta/src/main/java/com/sap/cloud/lm/sl/mta/resolvers/v2/RequiredDependencyReferenceResolver.java
- com.sap.cloud.lm.sl.mta/src/main/java/com/sap/cloud/lm/sl/mta/resolvers/v3/HookPlaceholderResolver.java
- com.sap.cloud.lm.sl.mta/src/main/java/com/sap/cloud/lm/sl/mta/resolvers/v3/HookReferenceResolver.java
- com.sap.cloud.lm.sl.mta/src/main/java/com/sap/cloud/lm/sl/mta/resolvers/v3/ModulePlaceholderResolver.java
- com.sap.cloud.lm.sl.mta/src/main/java/com/sap/cloud/lm/sl/mta/resolvers/v3/ModuleReferenceResolver.java
- com.sap.cloud.lm.sl.mta/src/main/java/com/sap/cloud/lm/sl/mta/util/MetadataUpdater.java
- com.sap.cloud.lm.sl.mta/src/main/java/com/sap/cloud/lm/sl/mta/util/PropertiesUtil.java
+ Add IntelliJ files to gitignore.
> Refactoring in mta package

- com.sap.cloud.lm.sl.common/pom.xml
- com.sap.cloud.lm.sl.mta/pom.xml
- pom.xml
> Set version to 1.75.0-SNAPSHOT

- com.sap.cloud.lm.sl.common/pom.xml
- com.sap.cloud.lm.sl.mta/pom.xml
- pom.xml
> Set version to 1.77.0-SNAPSHOT

- com.sap.cloud.lm.sl.common/src/main/java/com/sap/cloud/lm/sl/common/SLException.java
- com.sap.cloud.lm.sl.common/src/test/java/com/sap/cloud/lm/sl/common/util/GenericArgumentMatcher.java
- pom.xml
> Adopt Mockito 2.28.2

- com.sap.cloud.lm.sl.mta/src/main/java/com/sap/cloud/lm/sl/mta/model/Module.java
- com.sap.cloud.lm.sl.mta/src/main/java/com/sap/cloud/lm/sl/mta/model/NamedParametersContainer.java
- com.sap.cloud.lm.sl.mta/src/main/java/com/sap/cloud/lm/sl/mta/model/Resource.java
> Add common interface for name and parameters

- com.sap.cloud.lm.sl.mta/src/main/java/com/sap/cloud/lm/sl/mta/mergers/v2/ExtensionDescriptorMerger.java
- com.sap.cloud.lm.sl.mta/src/test/resources/com/sap/cloud/lm/sl/mta/handlers/v2/config-01.mtaext.json
- com.sap.cloud.lm.sl.mta/src/test/resources/mta/sample/v2/config-01.mtaext
- com.sap.cloud.lm.sl.mta/src/test/resources/mta/sample/v2/merged-04.yaml.json
- com.sap.cloud.lm.sl.mta/src/test/resources/mta/sample/v2/merged-05.yaml.json
> Allow extension descriptor to overwrite provided dependency parameters

- pom.xml
fixes code coverage in public sonar
> fix sonar code coverage

- pom.xml
> Increase version of jackson and spring

- pom.xml
spring.version - 5.2.3.RELEASE
> Fix vulas vulnerabilities

- com.sap.cloud.lm.sl.common/pom.xml
- com.sap.cloud.lm.sl.common/src/main/java/com/sap/cloud/lm/sl/common/util/JsonUtil.java
- pom.xml
> GACD inline content definition

- .gitignore
- com.sap.cloud.lm.sl.common/src/main/java/com/sap/cloud/lm/sl/common/AllowNulls.java
- com.sap.cloud.lm.sl.common/src/main/java/com/sap/cloud/lm/sl/common/MultiappsImmutablesStyle.java
- com.sap.cloud.lm.sl.common/src/main/java/com/sap/cloud/lm/sl/common/Nullable.java
- com.sap.cloud.lm.sl.common/src/main/java/com/sap/cloud/lm/sl/common/SkipNulls.java
- com.sap.cloud.lm.sl.common/src/main/java/com/sap/cloud/lm/sl/common/package-info.java
- com.sap.cloud.lm.sl.mta/src/main/java/com/sap/cloud/lm/sl/mta/package-info.java
- pom.xml
> Add support for Immutables

- pom.xml
> Adopt snakeyaml 1.26

- com.sap.cloud.lm.sl.common/src/main/java/com/sap/cloud/lm/sl/common/Messages.java
- com.sap.cloud.lm.sl.common/src/main/java/com/sap/cloud/lm/sl/common/util/MapUtil.java
- com.sap.cloud.lm.sl.common/src/test/java/com/sap/cloud/lm/sl/common/util/MapUtilTest.java
utility function for a boolean parameter added
> namespace changes - utility function added

- multiapps-common/src/main/java/org/cloudfoundry/multiapps/common/util/JsonUtil.java
- multiapps-common/src/test/java/org/cloudfoundry/multiapps/common/util/JsonUtilTest.java
ISSUE: LMCROSSITXSADEPLOY-2137
> Improve error message

- multiapps-common/src/main/java/org/cloudfoundry/multiapps/common/Messages.java
- multiapps-common/src/main/java/org/cloudfoundry/multiapps/common/util/JsonUtil.java
- multiapps-common/src/test/java/org/cloudfoundry/multiapps/common/util/JsonUtilTest.java
> Fix the way the error messages in JsonUtil

- .travis.yml
- multiapps-common-test/src/main/java/module-info.java
- multiapps-common/pom.xml
- multiapps-common/src/main/java/module-info.java
- multiapps-common/src/main/java/org/cloudfoundry/multiapps/common/Messages.java
- multiapps-common/src/main/java/org/cloudfoundry/multiapps/common/util/MapUtil.java
- multiapps-common/src/main/java/org/cloudfoundry/multiapps/common/util/XmlUtil.java
- multiapps-common/src/main/java/org/cloudfoundry/multiapps/common/util/yaml/YamlRepresenter.java
- multiapps-common/src/test/java/org/cloudfoundry/multiapps/common/util/JsonUtilTest.java
- multiapps-common/src/test/java/org/cloudfoundry/multiapps/common/util/MapUtilTest.java
- multiapps-mta/src/main/java/module-info.java
- multiapps-mta/src/main/java/org/cloudfoundry/multiapps/mta/handlers/ConfigurationParser.java
- pom.xml
> Adopt Java 11

- multiapps-common-test/src/main/java/org/cloudfoundry/multiapps/common/test/Tester.java
LMCROSSITXSADEPLOY-1633
added support for Set test Expectation
> extending Test.Expectation.Type

- multiapps-mta/src/main/java/org/cloudfoundry/multiapps/mta/Messages.java
- multiapps-mta/src/main/java/org/cloudfoundry/multiapps/mta/resolvers/PlaceholderResolver.java
- multiapps-mta/src/main/java/org/cloudfoundry/multiapps/mta/util/PropertiesUtil.java
- multiapps-mta/src/test/java/org/cloudfoundry/multiapps/mta/resolvers/v2/ModulePlaceholderResolverTest.java
- multiapps-mta/src/test/java/org/cloudfoundry/multiapps/mta/util/PropertiesUtilTest.java
- multiapps-mta/src/test/resources/org/cloudfoundry/multiapps/mta/resolvers/v2/mtad-with-single-elem-in-buildpacks.yaml
Pull request containing fix for issue: LMCROSSITXSADEPLOY-1700
Problem with casting arguments and lack of appropriate message.
> Corrected casting problem for singular/plural values and included UnitTests for the casting cases

- multiapps-common-test/pom.xml
- multiapps-common/pom.xml
- multiapps-mta/pom.xml
- pom.xml
Setting new version to 2.6.0-SNAPSHOT
> Set version to 2.6.0-SNAPSHOT

- pom.xml
* Junit 5.7.2
* junit-platform-launcher 1.8.2
* Mockito 4.2.0
> Bump OSS Junit dependencies

- multiapps-mta/src/main/java/org/cloudfoundry/multiapps/mta/Messages.java
- multiapps-mta/src/main/java/org/cloudfoundry/multiapps/mta/handlers/HandlerFactory.java
- multiapps-mta/src/main/java/org/cloudfoundry/multiapps/mta/handlers/v2/HandlerFactoryV2.java
- multiapps-mta/src/main/java/org/cloudfoundry/multiapps/mta/handlers/v2/ResourceBatchCalculator.java
- multiapps-mta/src/main/java/org/cloudfoundry/multiapps/mta/handlers/v2/SelectiveDeployChecker.java
- multiapps-mta/src/main/java/org/cloudfoundry/multiapps/mta/handlers/v3/HandlerFactoryV3.java
- multiapps-mta/src/main/java/org/cloudfoundry/multiapps/mta/handlers/v3/ResourceBatchCalculator.java
- multiapps-mta/src/main/java/org/cloudfoundry/multiapps/mta/handlers/v3/SelectiveDeployChecker.java
Description: 
Introducing selective deploy check for sequential resource processing
More information on why the change is needed here: LMCROSSITXSADEPLOY-1874
> Add selective deploy check for sequential resource processing

- multiapps-mta/src/main/java/org/cloudfoundry/multiapps/mta/handlers/HandlerFactory.java
- multiapps-mta/src/main/java/org/cloudfoundry/multiapps/mta/handlers/v2/HandlerFactoryV2.java
- multiapps-mta/src/main/java/org/cloudfoundry/multiapps/mta/handlers/v3/HandlerFactoryV3.java
- multiapps-mta/src/main/java/org/cloudfoundry/multiapps/mta/handlers/v3/SelectiveDeployChecker.java
Additional corner case coverage for LMCROSSITXSADEPLOY-1874.
> Edit SelectiveDeployChecker to validate only active resources

- pom.xml
> Increase snakeyaml version to 1.32

- pom.xml
> bump jackson to 2.13.4

- pom.xml
* junit to 5.9.2
* junit-platform to 1.9.2
* mockito to 4.11.0
* slf4j to 2.0.6
* jackson to 2.14.2
* jackson-databind to 2.14.2
> Bump OSS dependencies versions

- multiapps-mta/pom.xml
- multiapps-mta/src/main/java/module-info.java
- multiapps-mta/src/main/java/org/cloudfoundry/multiapps/mta/handlers/ArchiveHandler.java
- multiapps-mta/src/main/java/org/cloudfoundry/multiapps/mta/util/LimitedInputStream.java
- pom.xml
Remove dependency _commons-fileupload_
> Use a custom LimitedInputStream instead of filesupload library

- com.sap.cloud.lm.sl.mta/src/main/java/com/sap/cloud/lm/sl/mta/tags/YamlTaggedObjectsConstructor.java
- com.sap.cloud.lm.sl.mta/src/main/java/com/sap/cloud/lm/sl/mta/util/YamlRepresenter.java
- com.sap.cloud.lm.sl.mta/src/main/java/com/sap/cloud/lm/sl/mta/util/YamlUtil.java
- com.sap.cloud.lm.sl.mta/src/test/java/com/sap/cloud/lm/sl/mta/util/YamlUtilTest.java
- pom.xml
Bump snakeyaml version to 2.0
JIRA: LMCROSSITXSADEPLOY-2803
> Adopt snakeyaml 2.0

- com.sap.cloud.lm.sl.common/pom.xml
- com.sap.cloud.lm.sl.mta/pom.xml
- pom.xml
> [release] Set version to 1.67.14

- com.sap.cloud.lm.sl.common/pom.xml
- com.sap.cloud.lm.sl.mta/pom.xml
- pom.xml
Set version to 1.67.15-SNAPSHOT
> Set version to 1.67.15-SNAPSHOT

- pom.xml
> Update Outdated FOSS Components

- pom.xml
> Bumped junit-platform-launcher to 1.10.2

- .github/workflows/codeql.yml
- .github/workflows/main.yml
- .github/workflows/pull-request-build.yml
- pom.xml
> Adopt Java 17

- pom.xml
> LMCROSSITXSADEPLOY-2945 [XSA] Bump OSS dependencies versions for Spring

- com.sap.cloud.lm.sl.common/pom.xml
- com.sap.cloud.lm.sl.mta/pom.xml
- pom.xml
Update spring version to 5.3.39
> [release] Set version to 1.67.17

- multiapps-common/src/main/java/org/cloudfoundry/multiapps/common/util/MapUtil.java
Changed boolean to Boolean (need to use null as value in namespace task)
https://github.com/cloudfoundry/multiapps-controller/pull/1492
https://github.com/cloudfoundry/multiapps-cli-plugin/pull/204
https://github.com/SAP-samples/cf-mta-examples/pull/90
> Changed boolean to Boolean for namespace logic

- multiapps-common/src/main/java/org/cloudfoundry/multiapps/common/util/MapUtil.java
> Removed booleanValue() call

- pom.xml
Bump OSS dependencies versions found for Deploy Service 1.73.47
>  Bump OSS dependencies versions found for Deploy Service 1.73.47

- com.sap.cloud.lm.sl.common/pom.xml
- com.sap.cloud.lm.sl.mta/pom.xml
- pom.xml
[release] Set version to 1.67.18
> [release] Set version to 1.67.18

- com.sap.cloud.lm.sl.common/pom.xml
- com.sap.cloud.lm.sl.mta/pom.xml
- pom.xml
Set version to 1.67.19-SNAPSHOT
> Set version to 1.67.19-SNAPSHOT

- com.sap.cloud.lm.sl.common/pom.xml
- com.sap.cloud.lm.sl.mta/pom.xml
- pom.xml
> [release] Set version to 1.67.19

- multiapps-common/pom.xml
- multiapps-common/src/main/java/module-info.java
- multiapps-common/src/main/java/org/cloudfoundry/multiapps/common/util/DigestHelper.java
- multiapps-common/src/main/java/org/cloudfoundry/multiapps/common/util/XmlUtil.java
- pom.xml
> Migrate to jakarta.xml.bind

- com.sap.cloud.lm.sl.common/pom.xml
- com.sap.cloud.lm.sl.mta/pom.xml
- pom.xml
> Update Spring to 5.3.42

- multiapps-common-test/pom.xml
- multiapps-common/pom.xml
- multiapps-coverage/pom.xml
- multiapps-mta/pom.xml
- pom.xml
[release] Set version to 2.30.0
> [release] Set version to 2.30.0

- multiapps-common-test/pom.xml
- multiapps-common/pom.xml
- multiapps-coverage/pom.xml
- multiapps-mta/pom.xml
- pom.xml
> [release] Set version to 2.31.0

- multiapps-common-test/pom.xml
- multiapps-common/pom.xml
- multiapps-coverage/pom.xml
- multiapps-mta/pom.xml
- pom.xml
> [release] Set version to 2.36.0
